
package com.theknowledgeacademy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.0
 * 
 */
@WebService(name = "calservice", targetNamespace = "http://theknowledgeacademy.com")
public interface Calservice {


    /**
     * 
     * @param x
     * @param y
     * @return
     *     returns int
     */
    @WebMethod(action = "addAction")
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "addOp", targetNamespace = "http://theknowledgeacademy.com", className = "com.theknowledgeacademy.AddOp")
    @ResponseWrapper(localName = "addOpResponse", targetNamespace = "http://theknowledgeacademy.com", className = "com.theknowledgeacademy.AddOpResponse")
    public int addOp(
        @WebParam(name = "x", targetNamespace = "")
        int x,
        @WebParam(name = "y", targetNamespace = "")
        int y);

    /**
     * 
     * @param x
     * @param y
     * @return
     *     returns int
     */
    @WebMethod(action = "multiplyAction")
    @WebResult(name = "mulResult", targetNamespace = "")
    @RequestWrapper(localName = "multiplyOp", targetNamespace = "http://theknowledgeacademy.com", className = "com.theknowledgeacademy.MultiplyOp")
    @ResponseWrapper(localName = "multiplyOpResponse", targetNamespace = "http://theknowledgeacademy.com", className = "com.theknowledgeacademy.MultiplyOpResponse")
    public int multiplyOp(
        @WebParam(name = "x", targetNamespace = "")
        int x,
        @WebParam(name = "y", targetNamespace = "")
        int y);

}
